### PR TITLE
Issue/127 Fix Tracking

### LINKED ISSUE #127: Fix episode download tracking
Tracking now explicitly needs either an episode or network. At the moment only the audio file is given in the URL, which is not enough any more. While we're at it, we should make use of the new public URLs.

- maybe move TrackingController to `RadiatorWeb.Public`?
- route something like: `get "/:podcast_slug/:episode_slug/file/:file_id", TrackingController, :track`
- adjust controller to take the new parameters, see `Radiator.Tracking.track_download/1` for expected parameters

### PR DESCRIPTION
**Pull request by eteubert**
- updated tracking URLs and made them work again
- added AudioPublication to tracking
- add slug logic to AudioPublication
- update `AudioFile.public_url` (tracking URL) generation

closes #127

### CODE REVIEW

File: lib/radiator/directory/audio_publication.ex [hunk 1]
```diff
@@ -27,10 +30,14 @@ defmodule Radiator.Directory.AudioPublication do
...
       :publish_state,
-      :audio_id
+      :audio_id,
+      :title,
+      :slug
     ])
     |> validate_publish_state()
     |> maybe_set_published_at()
+    |> TitleSlug.maybe_generate_slug()
+    |> TitleSlug.unique_constraint()
```
Comment (monkeydom) [inline lib/radiator/directory/audio_publication.ex]: Shouldn't that just be scoped to a network?

File: lib/radiator/media/audio_file.ex [hunk 2]
```diff
@@ -44,12 +50,50 @@ defmodule Radiator.Media.AudioFile do
...
+    )
   end
 
-  def tracking_url(audio_file = %__MODULE__{}) do
-    RadiatorWeb.Router.Helpers.tracking_url(RadiatorWeb.Endpoint, :show, audio_file.id)
+  def tracking_url(audio_file = %__MODULE__{}, audio_publication = %AudioPublication{}) do
+    RadiatorWeb.Router.Helpers.tracking_url(
+      RadiatorWeb.Endpoint,
+      :track_audio_publication_file,
+      audio_publication.slug,
```
Comment (monkeydom) [inline lib/radiator/media/audio_file.ex]: I'd like to see network in here to, so audio publications aren't scoped globally for one radiator instance.

File: lib/radiator/directory/audio_publication.ex (hunk 1 above)
Comment (eteubert) [reply lib/radiator/directory/audio_publication.ex]: You mean representing an AudioPublication as network+audio in URLs, so we never need the title slug? My thought was that since it's very similar to an episode, it should behave in a similar way.

Comment (monkeydom) [reply lib/radiator/directory/audio_publication.ex]: No. Network slug and Audio slug.

Comment (eteubert) [reply lib/radiator/directory/audio_publication.ex]: Audio doesn't have a title/slug 🤔

Comment (monkeydom) [reply lib/radiator/directory/audio_publication.ex]: I meant network/slug and audiopublication/slug - sorry.
